language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DxyvYfPudLKMLeUFWZD71ZNZ3kjrDTbkeTum+AmcMR01zFQBMtRVJSfy+4UVk+nPrWv0es0sPYIcJ9QMRZi1xQFPyKOWvwvd1J4VX0OAmwvlnRbNwmZH+Y/vjj2y80+EU7dYp/3yqpRnFj+515N+ElQaEihgRVWyk1gUfx0R/qGD09CerqFDkjn4MoOulvu1sH5ykDo4sOS4qOs85c8bqEfa+QZw1rlf3wwgHw3OE1yY31HBW/h7ej2F3dg2zU5/ufct84HrzJ6V1NVo4kKHEokegyo0tbFMwqc/iuxwGYvaEFG/RyvTNVq9d24xWI/vmeLx/7VDX+5xlrG3KW2zZ8INSldEwZbGsglWhRZXFdIaY6a4F8k9dS0Qw5lNRB7CST5yjshGmHj+9I9xpKez98L+qn5jUT+BsWIxRpsZLvGmRfaJg9kT1li3Isw4fZFxCWe+vQDZiPlycAEfSpI3dBCX530AwB+tzD3LYOnvymCDVyIyk40pxB0GWV8JBt8RlaAyK9x0HuFWLwrwdFUbKuKTEuUM65+dlXrOMXSOquw8IjZHUs12H38m5PWt2ifjJDat1WrkLZ8EXkxo3CSE6DHmWYYKZ/qE+B8exZnmZ9chOaAVujbct/wULUxx/Cy/tQZkpMegE6LCefifnpXnkligDO11nduh1q8H6ULoaKg=
  app: ancient-refuge-84868